[package]
name = "potion-roguelike"
version = "0.1.0"
authors = ["WiredSound <maxoblack@yahoo.com>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
num = "0.3"
num-traits = "0.2"
num-derive = "0.3"
raylib = "3.0"
noise = "0.6"
serde_json = "1.0"
array-macro = "1.0"