version: '3'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 5678:5678
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: todo