unstable_features = true
max_width = 120
comment_width = 120
wrap_comments = true
trailing_comma = "Never"
use_small_heuristics = "Max"
brace_style = "PreferSameLine"
control_brace_style = "ClosingNextLine"
fn_args_layout = "Compressed"
where_single_line = true
reorder_impl_items = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
