unstable_features = true
max_width = 120
comment_width = 120
wrap_comments = true
brace_style = "PreferSameLine"
control_brace_style = "ClosingNextLine"
fn_args_layout = "Compressed"
fn_single_line = true
where_single_line = true
struct_lit_single_line = true
merge_imports = true
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
trailing_comma = "Never"
use_try_shorthand = true
use_small_heuristics = "Max"