[package]
name = "server"
version = "0.1.0"
authors = ["WiredSound <maxoblack@yahoo.com>"]
edition = "2018"

[dependencies]
core = { version = "*", path = "../" }

tungstenite = "0.11"

bincode = "1.3"
noise = "0.7"