name: client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    defaults:
      run:
        working-directory: client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install OpenGL
      run: sudo apt-get update && sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev libxi-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

